// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4pDjylnAI7id_bkVRlDCLUY5_AuesyV8',
    appId: '1:676914695479:web:04d316e8667bd9f78b1eb2',
    messagingSenderId: '676914695479',
    projectId: 'paytm-wallet-4d4b5',
    authDomain: 'paytm-wallet-4d4b5.firebaseapp.com',
    storageBucket: 'paytm-wallet-4d4b5.firebasestorage.app',
    measurementId: 'G-ZW3QX1LRSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZpN9Jb_aDYf5qBgLPr6PJuE6r1bbC5V8',
    appId: '1:676914695479:android:98df5f804181a52d8b1eb2',
    messagingSenderId: '676914695479',
    projectId: 'paytm-wallet-4d4b5',
    storageBucket: 'paytm-wallet-4d4b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi9yvlIN0RwcWYm-_zeXNf5Ma_9q_arqM',
    appId: '1:676914695479:ios:e1288be9bf0b30978b1eb2',
    messagingSenderId: '676914695479',
    projectId: 'paytm-wallet-4d4b5',
    storageBucket: 'paytm-wallet-4d4b5.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi9yvlIN0RwcWYm-_zeXNf5Ma_9q_arqM',
    appId: '1:676914695479:ios:e1288be9bf0b30978b1eb2',
    messagingSenderId: '676914695479',
    projectId: 'paytm-wallet-4d4b5',
    storageBucket: 'paytm-wallet-4d4b5.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4pDjylnAI7id_bkVRlDCLUY5_AuesyV8',
    appId: '1:676914695479:web:56768a7102bc358f8b1eb2',
    messagingSenderId: '676914695479',
    projectId: 'paytm-wallet-4d4b5',
    authDomain: 'paytm-wallet-4d4b5.firebaseapp.com',
    storageBucket: 'paytm-wallet-4d4b5.firebasestorage.app',
    measurementId: 'G-YYDVW9J06K',
  );
}
